name: janta
on: push
jobs:
  fazer-janta:
    runs-on: ubuntu-latest
    steps:
      - name: Ligar o fogo
        run: echo ligar o fogo

      - name: Fazer a janta
        run: echo fazer a janta

      - name: Apagar o fogo
        run: echo apagar o fogo

  fazer-cafe:
    needs: ['fazer-janta']
    runs-on: windows-latest
    steps:
      - name: fazer café
        run: Write-Host fazer café

  fazer-cafe-no-mac:
    needs: ['fazer-cafe']
    runs-on: macos-latest
    steps:
      - name: fazer café
        run: echo fazer café