name: ci
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Fazer checkout do repositorio
        uses: actions/checkout@v3
        
      - name: Visualizando repositorio
        run: ls -a

      - name: Instalar as dependencias
        run: yarn

      - name: Rodar o lint
        run: yarn lint

      - name: Rodar os testes
        run: yarn test

 